version: '3.8'

services:
  # Frontend (Astro)
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend
      - ollama

  # Backend API
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=8000
      - OLLAMA_API_URL=http://ollama:11434
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tetrix
      - POSTGRES_USER=tetrix
      - POSTGRES_PASSWORD=tetrix123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  ollama_data:
  postgres_data:
  redis_data:

networks:
  default:
    name: tetrix_network
