export declare const Permissions: {
    readonly AssignTask: "task.assign";
    readonly ReviewTask: "task.review";
    readonly AdminContactRead: "admin:contact:read";
    readonly AdminContactUpdate: "admin:contact:update";
    readonly AdminLogout: "admin:logout";
    readonly UserList: "user:list";
    readonly UserRead: "user:read";
    readonly UserUpdate: "user:update";
    readonly UserRoleUpdate: "user:role:update";
    readonly ProjectRead: "project:read";
};
export declare const DataAnnotatorPermissions: {
    readonly ProjectCreate: "project:create";
    readonly ProjectUpdate: "project:update";
    readonly ProjectDelete: "project:delete";
    readonly ProjectAssign: "project:assign";
    readonly TaskCreate: "task:create";
    readonly TaskAssign: "task:assign";
    readonly TaskSubmit: "task:submit";
    readonly TaskReview: "task:review";
    readonly TaskApprove: "task:approve";
    readonly TaskReject: "task:reject";
    readonly DatasetUpload: "dataset:upload";
    readonly DatasetDownload: "dataset:download";
    readonly DatasetAnnotate: "dataset:annotate";
    readonly QualityReview: "quality:review";
    readonly QualityApprove: "quality:approve";
    readonly QualityMetrics: "quality:metrics";
    readonly BillingView: "billing:view";
    readonly BillingManage: "billing:manage";
    readonly AnalyticsView: "analytics:view";
    readonly AnalyticsExport: "analytics:export";
};
export declare const AcademyPermissions: {
    readonly CourseEnroll: "course:enroll";
    readonly CourseView: "course:view";
    readonly CourseSubmit: "course:submit";
    readonly CourseGrade: "course:grade";
    readonly AssignmentSubmit: "assignment:submit";
    readonly AssignmentReview: "assignment:review";
    readonly AssignmentGrade: "assignment:grade";
    readonly ResourceAccess: "resource:access";
    readonly ResourceCreate: "resource:create";
    readonly ResourceShare: "resource:share";
    readonly ProgressView: "progress:view";
    readonly ProgressUpdate: "progress:update";
    readonly CertificateGenerate: "certificate:generate";
};
export declare const EnterprisePermissions: {
    readonly OrgCreate: "org:create";
    readonly OrgUpdate: "org:update";
    readonly OrgDelete: "org:delete";
    readonly OrgView: "org:view";
    readonly UserInvite: "user:invite";
    readonly UserRemove: "user:remove";
    readonly UserRoleAssign: "user:role:assign";
    readonly ApiAccess: "api:access";
    readonly ApiKeyManage: "api:key:manage";
    readonly ApiRateLimit: "api:rate:limit";
    readonly IntegrationCreate: "integration:create";
    readonly IntegrationUpdate: "integration:update";
    readonly IntegrationDelete: "integration:delete";
    readonly ReportGenerate: "report:generate";
    readonly ReportSchedule: "report:schedule";
    readonly ReportExport: "report:export";
};
export type Permission = typeof Permissions[keyof typeof Permissions] | typeof DataAnnotatorPermissions[keyof typeof DataAnnotatorPermissions] | typeof AcademyPermissions[keyof typeof AcademyPermissions] | typeof EnterprisePermissions[keyof typeof EnterprisePermissions];
