name: tetrix-production-fixed
services:
  - name: tetrix-frontend
    github:
      repo: tetrixcorps/miniverxe
      branch: main
      deploy_on_push: true
    build_command: |
      # Clean up any conflicting lockfiles
      rm -f package-lock.json yarn.lock npm-shrinkwrap.json .yarnrc .yarnrc.yml
      # Install dependencies (pnpm already installed by buildpack)
      pnpm install --frozen-lockfile
      # Build the application
      pnpm run build
    run_command: pnpm run start
    source_dir: /
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_AND_BUILD_TIME
      - key: HOST
        value: 0.0.0.0
        scope: RUN_AND_BUILD_TIME
      - key: PORT
        value: "8080"
        scope: RUN_AND_BUILD_TIME
      - key: TETRIX_DOMAIN
        value: tetrixcorp.com
        scope: RUN_AND_BUILD_TIME
      - key: JOROMI_DOMAIN
        value: joromi.tetrixcorp.com
        scope: RUN_AND_BUILD_TIME
      - key: CODE_ACADEMY_DOMAIN
        value: code-academy.tetrixcorp.com
        scope: RUN_AND_BUILD_TIME
      - key: CROSS_PLATFORM_SESSION_SECRET
        value: tetrix-joromi-session-secret-2024
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_API_TOKEN
        value: 544cdba462974e05adc5140211c0311c
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_SERVICE_PLAN_ID
        value: 01K1GYEHZAXEZVGDA34V3873KM
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_VIRTUAL_NUMBER
        value: "+16465799770"
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_BACKUP_NUMBER_1
        value: "+18888046762"
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_BACKUP_NUMBER_2
        value: "+12082792555"
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_BACKUP_NUMBER_3
        value: "+12082792555"
        scope: RUN_AND_BUILD_TIME
      - key: SINCH_CONVERSATION_PROJECT_ID
        value: 01K1GYEHZAXEZVGDA34V3873KM
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SINCH_API_KEY
        value: 544cdba462974e05adc5140211c0311c
        scope: RUN_AND_BUILD_TIME
      - key: NEXT_PUBLIC_SINCH_WIDGET_ID
        value: shango-widget-2024
        scope: RUN_AND_BUILD_TIME
      - key: SHANGO_SESSION_TIMEOUT
        value: "3600"
        scope: RUN_AND_BUILD_TIME
      - key: SHANGO_MAX_MESSAGES
        value: "1000"
        scope: RUN_AND_BUILD_TIME
      - key: SHANGO_DEFAULT_AGENT
        value: shango-general
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_API_KEY
        value: AIzaSyBvQjK8X9Y2Z3A4B5C6D7E8F9G0H1I2J3K
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_AUTH_DOMAIN
        value: fir-rtc-7b55d.firebaseapp.com
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_PROJECT_ID
        value: fir-rtc-7b55d
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_STORAGE_BUCKET
        value: fir-rtc-7b55d.appspot.com
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_MESSAGING_SENDER_ID
        value: "1073036366262"
        scope: RUN_AND_BUILD_TIME
      - key: FIREBASE_APP_ID
        value: 1:1073036366262:web:a76a0e270753f3e9497117
        scope: RUN_AND_BUILD_TIME
      - key: HOSTNAME
        value: 0.0.0.0
        scope: RUN_AND_BUILD_TIME
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
        scope: RUN_AND_BUILD_TIME
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    health_check:
      initial_delay_seconds: 60
      period_seconds: 15
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 5
      http_path: /api/health
domains:
  - domain: tetrixcorp.com
    type: PRIMARY
  - domain: www.tetrixcorp.com
    type: ALIAS
  - domain: api.tetrixcorp.com
    type: ALIAS
  - domain: iot.tetrixcorp.com
    type: ALIAS
  - domain: vpn.tetrixcorp.com
    type: ALIAS
  - domain: joromi.tetrixcorp.com
    type: ALIAS
  - domain: code-academy.tetrixcorp.com
    type: ALIAS
region: fra
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
ingress:
  rules:
    - match:
        path:
          prefix: /
      component:
        name: tetrix-frontend
features:
  - buildpack-stack=ubuntu-22
