name: Test Suite

on:
  push:
    branches: [ main, dev, staging ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run unit tests
      run: npm run test:unit
      env:
        NODE_ENV: test
        TETRIX_API_URL: http://localhost:4321
        JOROMI_URL: http://localhost:3000
        CODE_ACADEMY_URL: http://localhost:3001
    
    - name: Run functional tests
      run: npm run test:functional
      env:
        NODE_ENV: test
        TETRIX_API_URL: http://localhost:4321
        JOROMI_URL: http://localhost:3000
        CODE_ACADEMY_URL: http://localhost:3001
    
    - name: Run integration tests
      run: npm run test:integration
      env:
        NODE_ENV: test
        TETRIX_API_URL: http://localhost:4321
        JOROMI_URL: http://localhost:3000
        CODE_ACADEMY_URL: http://localhost:3001
    
    - name: Run all tests
      run: npm run test
      env:
        NODE_ENV: test
        TETRIX_API_URL: http://localhost:4321
        JOROMI_URL: http://localhost:3000
        CODE_ACADEMY_URL: http://localhost:3001
    
    - name: Generate coverage report
      run: npm run test:coverage
      env:
        NODE_ENV: test
        TETRIX_API_URL: http://localhost:4321
        JOROMI_URL: http://localhost:3000
        CODE_ACADEMY_URL: http://localhost:3001
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
